#!/system/bin/sh
### Bootroot environment

## Define chroot sudo path
CHROOT_EXEC=/usr/bin/sudo

## Define chroot paths
CHROOT_SYSTEM_PATH=`cat /data/data/material.hunter/shared_prefs/material.hunter.xml | sed -n 's/.*<string name="chroot_system_path">\(.*\)<\/string>/\1/p'`
if [ -z $CHROOT_SYSTEM_PATH ]; then
    CHROOT_SYSTEM_PATH="/data/local/nhsystem"
fi
directory=`cat /data/data/material.hunter/shared_prefs/material.hunter.xml | sed -n 's/.*<string name="chroot_directory">\(.*\)<\/string>/\1/p'`
if [ -z $directory ]; then
    directory="chroot"
fi

## Combine android $PATH to chroot $PATH
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH

## Define busybox path
BUSYBOX=`which busybox | head -n1`
if [ -z $BUSYBOX ]; then
    if [ -x "/system/xbin/busybox" ]; then
        BUSYBOX="/system/xbin/busybox"
    elif [ -x "/system/bin/busybox" ]; then
        BUSYBOX="/system/bin/busybox"
    fi
fi

## Define chroot settings
mount_sdcard=`cat /data/data/material.hunter/shared_prefs/material.hunter.xml | sed -n 's/.*<boolean name="mount_sdcard" value="\(.*\)" \/>/\1/p'`
mount_system=`cat /data/data/material.hunter/shared_prefs/material.hunter.xml | sed -n 's/.*<boolean name="mount_system" value="\(.*\)" \/>/\1/p'`
mount_data=`cat /data/data/material.hunter/shared_prefs/material.hunter.xml | sed -n 's/.*<boolean name="mount_data" value="\(.*\)" \/>/\1/p'`

## Define MNT (full path to target chroot)
MNT="$CHROOT_SYSTEM_PATH/$directory"

HOSTNAME=`cat /data/data/material.hunter/shared_prefs/material.hunter.xml | grep "\"hostname\"" | sed "s/^.*\"hostname\">\(.*\)<\/string>/\1/g"`
if [ -z $HOSTNAME ]; then
    HOSTNAME="android"
fi