#!/system/bin/sh
### Bootroot environment

## Define chroot sudo path
CHROOT_EXEC=/usr/bin/sudo

## Define base system path
NHSYSTEM_PATH=/data/local/nhsystem

## Combine android $PATH to chroot $PATH
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH

## Define busybox path
BUSYBOX=`which busybox | head -n1`
if [ -z "$BUSYBOX" ]; then
    if [ -x "/system/xbin/busybox" ]; then
        BUSYBOX="/system/xbin/busybox"
    elif [ -x "/system/bin/busybox" ]; then
        BUSYBOX="/system/bin/busybox"
    fi
fi

## Define chroot settings
sdcard_part=`cat /data/data/material.hunter/shared_prefs/material.hunter.xml | grep "\"sdcard_part\"" | sed "s/^.*\"sdcard_part\">\(.*\)<\/string>/\1/g"`
system_part=`cat /data/data/material.hunter/shared_prefs/material.hunter.xml | grep "\"system_part\"" | sed "s/^.*\"system_part\">\(.*\)<\/string>/\1/g"`

## Define executable variables
MNT=`cat /data/data/material.hunter/shared_prefs/material.hunter.xml | grep "\"chroot_directory_path\"" | sed "s/^.*\"chroot_directory_path\">\(.*\)<\/string>/\1/g"`

HOSTNAME=`cat /data/data/material.hunter/shared_prefs/material.hunter.xml | grep "\"hostname\"" | sed "s/^.*\"hostname\">\(.*\)<\/string>/\1/g"`
if [ -z $HOSTNAME ]; then
    HOSTNAME="android"
fi