#!/system/bin/sh

shels=$(readlink -f $0)
. ${shels%/*}/bootroot_env

if [ -z "$MNT" ]; then
    echo "[-] \$MNT variable isn't defined, please run the MaterialHunter app first."
    exit 2
fi

if [ ! -d "$MNT" ]; then
    echo "[-] Chroot directory doesn't exist."
    echo "[!] Don't do stupid things."
    exit 2
fi

if [ ! -x "$MNT/$CHROOT_EXEC" ]; then
    echo "[-] sudo not installed. This is not a MaterialHunter problem!"
    echo "Solutions:"
    echo "1. Try using busybox to login and install it"
    echo "2. Contact chroot builder"
    exit 2
fi

# Unset Android/Termux variables for stability
unset ANDROID_ART_ROOT
unset ANDROID_DATA
unset ANDROID_ROOT
unset LD_PRELOAD
unset PREFIX
unset TMPDIR

# TODO: избавиться от костылей в этой части (вызов из сервисов)
$BUSYBOX chroot $MNT $CHROOT_EXEC -E PATH=$PATH su -c "$*"