#!/system/bin/sh

# this runs before the chroot services

if [ ! $? -eq 0 ]; then
    exit 1
fi

USERINIT_SCRIPT_PATH=$(readlink -f $0)
. /data/data/material.hunter/files/scripts/bootroot_env

## Validate busybox path.
if [ -z "$BUSYBOX" ]; then
    echo "[-] Busybox isn't installed or busybox is not granted execute permission, if you did have it installed, please symlink it to /system/xbin and grant it the permission."
    exit 1
fi

## Validate Chroot path.
if [ ! -d "$MNT" ]; then
    echo "[-] \"$MNT\" directory not exist!"
    echo "[!] Click the button [INSTALL] down below now!"
    exit 2
fi
if [ -z "$MNT" ]; then
    echo "[-] The \$MNT variable is not defined, please the MaterialHunter app first."
    exit 2
fi

## Define chroot shell executable path.
if [ ! -x $MNT$CHROOT_EXEC ]; then
    echo "[-] Your chroot has no \"sudo\" installed, please install it manually first."
    echo "[-] Also make sure your chroot isn't corrupted."
    exit 2
fi

if sh /data/data/material.hunter/files/scripts/chrootmgr -p $MNT -c 'status'; then
    IS_CHROOT_MOUNTED=0
    echo "[+] IS_CHROOT_MOUNTED: Yes"
else
    IS_CHROOT_MOUNTED=1
    echo "[-] IS_CHROOT_MOUNTED: No"
fi

echo "[!] Starting user defined custom commands..."
while IFS= read -r line || [ -n "$line" ]; do
    read -r SENDTO CMD <<< $line
    if [ "$SENDTO" = "android" ]; then
        echo "[!] Executing: sh -c \"$CMD\""
        sh -c "$CMD"
    elif [ "$SENDTO" = "chroot" ]; then
        if [ $IS_CHROOT_MOUNTED -eq 0 ]; then
            echo "[!] Executing: $BUSYBOX chroot $MNT $CHROOT_EXEC -E PATH=$PATH su -c \"$CMD\""
            $BUSYBOX chroot $MNT $CHROOT_EXEC -E PATH=$PATH su -c "$CMD"
        else
            echo "[!] Chroot isn't mounted, skip executing $BUSYBOX chroot $MNT $CHROOT_EXEC -E PATH=$PATH $CMD"
        fi
    fi
done < /data/data/material.hunter/files/scripts/runonboot_services
echo "[+] User defined custom commands has been all executed."
