#!/system/bin/sh

# This runs after the Chroot has been started.

if [ ! $? -eq 0 ]; then
    exit 1
fi

. /data/data/material.hunter/files/scripts/bootroot_env

echo "[!] Starting user defined services..."
while IFS= read -r line; do
    if [ ! -z "$line" ]; then
        $BUSYBOX chroot $MNT $CHROOT_EXEC -E PATH=$PATH su -c "$line"
    fi
done < /data/data/material.hunter/files/scripts/services
echo "[+] Services should be started!"