#!/system/bin/sh

# This runs after the Chroot has been started.

if [ ! $? -eq 0 ]; then
    exit 1
fi

USERINIT_SCRIPT_PATH=$(readlink -f $0)
. /data/data/material.hunter/files/scripts/bootroot_env

## Validate busybox path.
if [ -z "$BUSYBOX" ]; then
    echo "[-] Busybox isn't installed or busybox isn't granted execute permission, if you did have it installed, please symlink it to /system/xbin and grant it the permission."
    exit 1
fi

## Validate Chroot path.
if [ ! -d "$MNT" ]; then
    echo "[-] \"$MNT\" directory not exist!"
    echo "[!] Click the button [INSTALL] down below now!"
    exit 2
fi
if [ -z "$MNT" ]; then
    echo "[-] The \$MNT variable is not defined, please the MaterialHunter app first."
    exit 2
fi

## Define chroot shell executable path.
if [ ! -x $MNT$CHROOT_EXEC ]; then
    echo "[-] Your chroot has no \"sudo\" installed, please install it manually first."
    echo "[-] Also make sure your chroot isn't corrupted."
    exit 2
fi

echo "[!] Starting user defined services..."
while IFS= read -r line; do
    if [ ! -z "$line" ]; then
        $BUSYBOX chroot $MNT $CHROOT_EXEC -E PATH=$PATH su -c "$line"
    fi
done < /data/data/material.hunter/files/scripts/services
echo "[+] Services should be started!"
