#!/system/bin/sh

USERINIT_SCRIPT_PATH=$(readlink -f $0)
sh ${USERINIT_SCRIPT_PATH%/*/*/*}/scripts/bootkali_init
mount -o rw,remount /
ln -sf ${USERINIT_SCRIPT_PATH%/*/*/*}/scripts/bootkali /system/xbin/
ln -sf ${USERINIT_SCRIPT_PATH%/*/*/*}/scripts/bootkali_bash /system/xbin/
ln -sf ${USERINIT_SCRIPT_PATH%/*/*/*}/scripts/bootkali_env /system/xbin/
ln -sf ${USERINIT_SCRIPT_PATH%/*/*/*}/scripts/bootkali_init /system/xbin/
ln -sf ${USERINIT_SCRIPT_PATH%/*/*/*}/scripts/bootkali_log /system/xbin/
ln -sf ${USERINIT_SCRIPT_PATH%/*/*/*}/scripts/bootkali_login /system/xbin/
ln -sf ${USERINIT_SCRIPT_PATH%/*/*/*}/scripts/bin/busybox_nh /system/xbin/
mount -o ro,remount /